package ClientMVC.View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import ClientMVC.Controller;
import Utilities.Vehicle;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Date;
import java.util.List;

/**
 *
 * @author INSTRUCT-D522lab
 */
public class AdminHomeView extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHomeView() {
        initComponents();
        addTabChangeListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();
        shadowRenderer1 = new raven.tabbed.ShadowRenderer();
        jPanel1 = new javax.swing.JPanel();
        managecarlistingtable = new raven.tabbed.TabbedPaneCustom();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewbooking = new javax.swing.JTable();
        btnApplyBooking = new javax.swing.JButton();
        refreshbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaAnnouncements = new javax.swing.JTextArea();
        btnPostAnnouncement = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ManageUserTable = new javax.swing.JTable();
        btnSearchManageUser = new javax.swing.JButton();
        txtFieldSearchManageUser = new javax.swing.JTextField();
        btnDeleteManageUser = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnApplyUser = new javax.swing.JButton();
        btnCancelUser = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ManageCarTable = new javax.swing.JTable();
        txtFieldSearchManageCar = new javax.swing.JTextField();
        btnSearchManageCar = new javax.swing.JButton();
        btnDeleteManageCar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnCancelManageCar = new javax.swing.JButton();
        btnApplyManageCar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        PurchaseHistoryTable = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        usernameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PlateTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PriceAddAdminTF = new javax.swing.JTextField();
        addbtnVehicle = new javax.swing.JToggleButton();
        modelTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        refreshBTN = new javax.swing.JButton();
        bookBTNadmin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel7 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnLogout = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        managecarlistingtable.setBackground(new java.awt.Color(255, 153, 51));

        tableViewbooking.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "Vehicle ID", "Model", "Status", "Plate Number", "Price", "Username", "Accept", "Decline"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableViewbooking);

        btnApplyBooking.setBackground(new java.awt.Color(255, 102, 0));
        btnApplyBooking.setText("Apply Changes");
        btnApplyBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyBookingActionPerformed(evt);
            }
        });

        refreshbtn.setText("Refresh");
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(555, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnApplyBooking))
                                .addGap(451, 451, 451))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApplyBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(refreshbtn)
                                .addGap(0, 45, Short.MAX_VALUE))
        );

        managecarlistingtable.addTab("View Booking", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtAreaAnnouncements.setColumns(20);
        txtAreaAnnouncements.setLineWrap(true);
        txtAreaAnnouncements.setRows(5);
        txtAreaAnnouncements.setSelectionColor(new java.awt.Color(255, 102, 51));
        jScrollPane4.setViewportView(txtAreaAnnouncements);

        btnPostAnnouncement.setBackground(new java.awt.Color(255, 102, 0));
        btnPostAnnouncement.setText("Post");
        btnPostAnnouncement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostAnnouncementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(133, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(133, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(480, 480, 480)
                                .addComponent(btnPostAnnouncement, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPostAnnouncement)
                                .addContainerGap(276, Short.MAX_VALUE))
        );

        managecarlistingtable.addTab("Announcements", jPanel3);

        ManageUserTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null,null}
                },
                new String [] {
                        "User Name", "First Name", "Last Name", "Email", "Phone Number", "Account Type","Status", "Ban User", "Unban User"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false,false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ManageUserTable);

        btnSearchManageUser.setText("Search");
        btnSearchManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchManageUserActionPerformed(evt);
            }
        });


        btnDeleteManageUser.setText("Delete");
        btnDeleteManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteManageUserActionPerformed(evt);
            }
        });

        btnApplyUser.setBackground(new java.awt.Color(255, 102, 51));
        btnApplyUser.setText("Apply Changes");
        btnApplyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyUserActionPerformed(evt);
            }
        });

        btnCancelUser.setText("Refresh");
        btnCancelUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(470, 470, 470)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCancelUser)
                                        .addComponent(btnApplyUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnApplyUser)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelUser)
                                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtFieldSearchManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchManageUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteManageUser)
                                .addContainerGap())
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFieldSearchManageUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSearchManageUser)
                                        .addComponent(btnDeleteManageUser))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        managecarlistingtable.addTab("Manage User", jPanel4);

        ManageCarTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null}
                },
                new String [] {
                        "Vehicle ID", "Model", "Status", "Plate Number", "Price"
                }
        ));
        jScrollPane5.setViewportView(ManageCarTable);

        btnSearchManageCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldSearchManageCarActionPerformed(evt);
            }
        });

        btnSearchManageCar.setText("Search");

        btnDeleteManageCar.setText("Delete");
        btnDeleteManageCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteManageCarActionPerformed(evt);
            }
        });

        btnCancelManageCar.setText("Refresh");
        btnCancelManageCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelManageCarActionPerformed(evt);
            }
        });

        btnApplyManageCar.setBackground(new java.awt.Color(255, 102, 51));
        btnApplyManageCar.setText("Apply Changes");
        btnApplyManageCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyManageCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnCancelManageCar)
                                        .addComponent(btnApplyManageCar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(470, 470, 470))
        );
        jPanel10Layout.setVerticalGroup(
                jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnApplyManageCar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelManageCar)
                                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtFieldSearchManageCar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchManageCar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteManageCar)
                                .addContainerGap())
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFieldSearchManageCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSearchManageCar)
                                        .addComponent(btnDeleteManageCar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        managecarlistingtable.addTab("Manage Car Listing", jPanel5);

        PurchaseHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "Username", "Vehicle ID", "Model", "Status", "Plate Number", "Price", "Date Booked", "Days", "Admin Fee"
                }
        ));
        jScrollPane7.setViewportView(PurchaseHistoryTable);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );

        managecarlistingtable.addTab("Purchase History", jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        usernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Username:");

        PlateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlateTFActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Plate No:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Price:");

        PriceAddAdminTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceAddAdminTFActionPerformed(evt);
            }
        });

        addbtnVehicle.setBackground(new java.awt.Color(255, 102, 0));
        addbtnVehicle.setText("Add");
        addbtnVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnVehicle(evt);
            }
        });

        modelTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTFActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Model:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel12Layout.createSequentialGroup()
                                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel3)
                                                                .addGap(18, 18, 18))
                                                        .addGroup(jPanel12Layout.createSequentialGroup()
                                                                .addGap(114, 114, 114)
                                                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel5))
                                                                .addGap(23, 23, 23)))
                                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(PlateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(PriceAddAdminTF, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel12Layout.createSequentialGroup()
                                                .addGap(257, 257, 257)
                                                .addComponent(addbtnVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(673, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(modelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PlateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PriceAddAdminTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addComponent(addbtnVehicle)
                                .addContainerGap(202, Short.MAX_VALUE))
        );

        managecarlistingtable.addTab("Add Vehicle", jPanel12);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null}
                },
                new String [] {
                        "ID", "Model", "Status", "Plate No.", "Price", "Username"
                }
        ));
        jScrollPane8.setViewportView(bookingTable);

        refreshBTN.setBackground(new java.awt.Color(102, 255, 102));
        refreshBTN.setText("Refresh");
        refreshBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshPendingActionPerformed(evt);
            }
        });

        bookBTNadmin.setBackground(new java.awt.Color(0, 255, 51));
        bookBTNadmin.setText("Book");
        bookBTNadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBTNadminActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Date From");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Date To");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(refreshBTN))
                        .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel15Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(300, 300, 300))
                                        .addGroup(jPanel15Layout.createSequentialGroup()
                                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bookBTNadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14))))
        );
        jPanel15Layout.setVerticalGroup(
                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel15Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(refreshBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7))
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel15Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(58, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bookBTNadmin)
                                                .addGap(66, 66, 66))))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        managecarlistingtable.addTab("Booking", jPanel13);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        getActivityLog(jTextArea1);
        jScrollPane9.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                .addContainerGap(20, Short.MAX_VALUE)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
        );
        jPanel16Layout.setVerticalGroup(
                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel16Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(38, Short.MAX_VALUE))
        );

        managecarlistingtable.addTab("Activity Log", jPanel16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("WELCOME ADMIN!");
        jScrollPane6.setViewportView(jTextArea2);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnLogout)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(managecarlistingtable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(managecarlistingtable, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnVehicle(ActionEvent evt) {
        SwingUtilities.invokeLater(() -> {
            String user = usernameTF.getText();
            String modelText = modelTF.getText();
            String plateNumberText = PlateTF.getText();
            String priceText = PriceAddAdminTF.getText();

            try {
                double priceValue = Double.parseDouble(priceText);
                Controller.getInstance().addVehicleAdmin(user,modelText, plateNumberText, priceValue);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please enter valid values! all fields shouldn't be empty and price can't be lower than 0", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        SwingUtilities.invokeLater(() -> {
            try {
                ClientMVC.Controller.getInstance().logout();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            dispose();
        });
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void modelTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTFActionPerformed

    private void PriceAddAdminTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceAddAdminTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceAddAdminTFActionPerformed

    private void PlateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlateTFActionPerformed

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTFActionPerformed

    private void btnApplyManageCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyManageCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApplyManageCarActionPerformed

    private void btnCancelManageCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelManageCarActionPerformed
        SwingUtilities.invokeLater(() -> {
            Controller.getInstance().refreshCarsData();
        });
    }//GEN-LAST:event_btnCancelManageCarActionPerformed

    private void btnDeleteManageCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteManageCarActionPerformed
        SwingUtilities.invokeLater(() -> {
            int selectedRow = ManageCarTable.getSelectedRow();
            if (selectedRow != -1) {
                String vehicleModel = (String) ManageCarTable.getValueAt(selectedRow, 1);
                String plateNo = (String) ManageCarTable.getValueAt(selectedRow, 3); // Assuming plate number is in the fourth column

                // Ask for user confirmation
                int confirmResult = JOptionPane.showConfirmDialog(this,
                        "Are you sure you want to cancel the booking for " + vehicleModel + " with plate number " + plateNo + "?",
                        "Confirm Cancellation", JOptionPane.YES_NO_OPTION);

                if (confirmResult == JOptionPane.YES_OPTION) {
                    try {
                        // Call the cancelBooking method in the admin controller
                        boolean cancellationSuccessful = Controller.getInstance().deleteVehicleAdmin(vehicleModel, plateNo);

                        if (cancellationSuccessful) {
                            // If cancellation is successful, remove the row from the table
                            DefaultTableModel model = (DefaultTableModel) ManageUserTable.getModel();
                            model.removeRow(selectedRow);
                        }
                    } catch (Exception ignore) {

                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a vehicle to cancel.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            Controller.getInstance().refreshCarsData();
        });
    }//GEN-LAST:event_btnDeleteManageCarActionPerformed

    private void txtFieldSearchManageCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldSearchManageCarActionPerformed
        SwingUtilities.invokeLater(() -> {
            Controller.getInstance().handleVehicleSearchButtonAdmin();
        });
    }//GEN-LAST:event_txtFieldSearchManageCarActionPerformed

    private void btnApplyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyUserActionPerformed
        // Fetch the table model
        DefaultTableModel model = (DefaultTableModel) getManageUserTable().getModel();

        // Iterate through the table rows
        for (int i = 0; i < model.getRowCount(); i++) {
            String user =model.getValueAt(i, 0).toString();
            String status =model.getValueAt(i, 6).toString();
            Boolean accept = (Boolean) model.getValueAt(i, 7); // Accept checkbox
            Boolean decline = (Boolean) model.getValueAt(i, 8); // Decline checkbox

            // Check if both checkboxes are ticked for the same row
            if (accept != null && decline != null && accept && decline) {
                JOptionPane.showMessageDialog(this, "Please select either Ban or Unban", "Both checkboxes are ticked!", JOptionPane.WARNING_MESSAGE);
                // Skip processing this row
                continue;
            } else if (accept != null && accept) {
                // If the accept checkbox is ticked, approve the vehicle
                String decision = "Ban";
                Controller.getInstance().banUser(user, decision,status);
            } else if (decline != null && decline) {
                // If the decline checkbox is ticked, deny the vehicle
                String decision = "Unban";
                Controller.getInstance().unbanUser(user, decision,status);
            }

            // Reset checkboxes for the processed row
            model.setValueAt(false, i, 7); // Uncheck accept checkbox
            model.setValueAt(false, i, 8); // Uncheck decline checkbox
        }
        // After processing all rows, refresh the pending requests
        Controller.getInstance().refreshClientData();
    }//GEN-LAST:event_btnApplyUserActionPerformed

    private void btnDeleteManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteManageUserActionPerformed
        SwingUtilities.invokeLater(() -> {
            int selectedRow = ManageUserTable.getSelectedRow();
            if (selectedRow != -1) {
                String Username = (String) ManageUserTable.getValueAt(selectedRow, 0);


                // Ask for user confirmation
                int confirmResult = JOptionPane.showConfirmDialog(this,
                        "Are you sure you want to delete the user  " + Username + "?",
                        "Confirm Cancellation", JOptionPane.YES_NO_OPTION);

                if (confirmResult == JOptionPane.YES_OPTION) {
                    try {
                        // Call the cancelBooking method in the admin controller
                        boolean cancellationSuccessful = Controller.getInstance().deleteUser(Username);

                        if (cancellationSuccessful) {
                            // If cancellation is successful, remove the row from the table
                            DefaultTableModel model = (DefaultTableModel) ManageUserTable.getModel();
                            model.removeRow(selectedRow);
                        }
                    } catch (Exception e) {
                        // Handle exceptions during cancellation
                        JOptionPane.showMessageDialog(this, "Error during cancellation: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a vehicle to cancel.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }//GEN-LAST:event_btnDeleteManageUserActionPerformed



    private void btnSearchManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchManageUserActionPerformed
        SwingUtilities.invokeLater(() -> {
            Controller.getInstance().handleClientSearchButton();
        });
    }//GEN-LAST:event_btnSearchManageUserActionPerformed

    private void btnPostAnnouncementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostAnnouncementActionPerformed
        String announcementText = txtAreaAnnouncements.getText();
        Controller.getInstance().sendAnnouncement(announcementText);
    }//GEN-LAST:event_btnPostAnnouncementActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        SwingUtilities.invokeLater(() -> {
            Controller.getInstance().refreshPendingRequests();
        });
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void btnApplyBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyBookingActionPerformed
        // Fetch the table model
        DefaultTableModel model = (DefaultTableModel) tableViewbooking.getModel();

        // Iterate through the table rows
        for (int i = 0; i < model.getRowCount(); i++) {
            int vehicleId = Integer.parseInt(model.getValueAt(i, 0).toString());
            boolean accept = (boolean) model.getValueAt(i, 6); // Accept checkbox
            boolean decline = (boolean) model.getValueAt(i, 7); // Decline checkbox

            // Check if both checkboxes are ticked for the same row
            if (accept && decline) {
                // If both checkboxes are selected, deselect the previous one
                model.setValueAt(false, i, 6); // Uncheck accept checkbox
                model.setValueAt(false, i, 7); // Uncheck decline checkbox
                JOptionPane.showMessageDialog(this, "Please select either Accept or Decline", "Both checkbox are ticked!", JOptionPane.WARNING_MESSAGE);
            } else if (accept) {
                String decision = "accept";
                // If the accept checkbox is ticked, approve the vehicle
                Controller.getInstance().approveVehicle(String.valueOf(vehicleId),decision);
                // Uncheck the decline checkbox for the same row
                model.setValueAt(false, i, 7);
            } else if (decline) {
                // If the decline checkbox is ticked, deny the vehicle
                String decision = "decline";
                Controller.getInstance().denyVehicle(String.valueOf(vehicleId),decision);
                // Uncheck the accept checkbox for the same row
                model.setValueAt(false, i, 6);
            }
        }

        // After processing all rows, refresh the pending requests
        Controller.getInstance().refreshPendingRequests();
    }//GEN-LAST:event_btnApplyBookingActionPerformed

    private void btnRefreshUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshUserActionPerformed
        SwingUtilities.invokeLater(() -> {
            Controller.getInstance().refreshClientData();
        });
    }

    private void refreshPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshPendingActionPerformed
        SwingUtilities.invokeLater(() -> {
            Controller.getInstance().getVehicles();
        });
    }//GEN-LAST:event_refreshPendingActionPerformed

    private void setTableViewBooking() {
        SwingUtilities.invokeLater(() -> {
            Controller.getInstance().ViewBookingData();
        });
    }

    private void setManageUserTable() {
        SwingUtilities.invokeLater(() -> {
            Controller.getInstance().refreshClientData();
        });
    }

    private void setManageCarTable() {
        SwingUtilities.invokeLater(() -> {
            Controller.getInstance().refreshCarsData();
        });
    }

    private void setPurchaseHistoryTable() {
        SwingUtilities.invokeLater(() -> {
            Controller.getInstance().PurchaseHistoryData();
        });
    }

    private void setBookingTable() {
        SwingUtilities.invokeLater(() -> {
            Controller.getInstance().getVehicles();
        });
    }

    private void setActivityLog() {
        int delay = 30000; // Delay in milliseconds (e.g., 5000ms = 5 seconds)
        Timer timer = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SwingUtilities.invokeLater(() -> {
                    jTextArea1.setText("");
                    Controller.getInstance().getActivityLog(jTextArea1);
                });
            }
        });

        // Start the timer
        timer.start();
    }

    public void updatePendingRequestsTable(List<Vehicle> vehicles) {
        DefaultTableModel model = (DefaultTableModel) tableViewbooking.getModel();
        model.setRowCount(0);

        for (Vehicle vehicle : vehicles) {
            model.addRow(new Object[]{
                    vehicle.getId(),
                    vehicle.getModel(),
                    vehicle.getStatus(),
                    vehicle.getPlateNumber(),
                    vehicle.getPrice(),
                    vehicle.getUsername(),
                    false, // Accept checkbox default to false
                    false  // Decline checkbox default to false
            });
        }
    }

    private void addTabChangeListener() {
        managecarlistingtable.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                JTabbedPane sourceTabbedPane = (JTabbedPane) e.getSource();
                int selectedIndex = sourceTabbedPane.getSelectedIndex();
                if (selectedIndex == 0) {
                    setTableViewBooking();
                } else if (selectedIndex == 2) {
                    setManageUserTable();
                } else if (selectedIndex == 3) {
                    setManageCarTable();
                } else if (selectedIndex == 4) { // Assuming Purchase History tab index is 2
                    setPurchaseHistoryTable();
                } else if (selectedIndex == 6) {
                    setBookingTable();
                } else if (selectedIndex == 7) {
                    setActivityLog();
                }
            }
        });
    }

    public static JTable getManageUserTable() {
        return ManageUserTable;
    }
    public static JTextField getTxtFieldSearchManageUser() {
        return txtFieldSearchManageUser;
    }
    public static JTable getManageCarTable() {
        return ManageCarTable;
    }
    public static JTextField getTxtFieldSearchManageCar() {
        return txtFieldSearchManageCar;
    }
    public static JTable getPurchaseHistory() {
        return PurchaseHistoryTable;
    }
    public static JTable getBookingResult() {
        return bookingTable;
    }
    public static JTextArea getActivityLog(JTextArea jTextArea1) {
        return new JTextArea();
    }

    private void btnCancelUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelUserActionPerformed

    private void bookBTNadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBTNadminActionPerformed
        SwingUtilities.invokeLater(() -> {
            int selectedRow = bookingTable.getSelectedRow();
            if (selectedRow != -1) {
                String vehicleModel = (String) bookingTable.getValueAt(selectedRow, 1);
                String plateNo = (String) bookingTable.getValueAt(selectedRow, 3);
                Date from = jCalendar2.getDate();
                Date To = jCalendar1.getDate();
                Boolean status = Controller.getInstance().bookForPendingVehicleAdmin(vehicleModel, plateNo,from,To);
                try {
                    if (status) {
                        DefaultTableModel model = (DefaultTableModel) bookingTable.getModel();
                        model.removeRow(selectedRow);
                    }
                }catch (NullPointerException Ignore) {
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please select a vehicle to cancel.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        });
    }//GEN-LAST:event_bookBTNadminActionPerformed

    private void refreshBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable ManageCarTable;
    private static javax.swing.JTable ManageUserTable;
    private javax.swing.JTextField PlateTF;
    private javax.swing.JTextField PriceAddAdminTF;
    private static javax.swing.JTable PurchaseHistoryTable;
    private javax.swing.JToggleButton addbtnVehicle;
    private javax.swing.JButton bookBTNadmin;
    private javax.swing.JButton btnApplyBooking;
    private javax.swing.JButton btnApplyManageCar;
    private javax.swing.JButton btnApplyUser;
    private javax.swing.JButton btnCancelManageCar;
    private javax.swing.JButton btnCancelUser;
    private javax.swing.JButton btnDeleteManageCar;
    private javax.swing.JButton btnDeleteManageUser;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPostAnnouncement;
    private javax.swing.JButton btnSearchManageCar;
    private javax.swing.JButton btnSearchManageUser;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private static javax.swing.JTable bookingTable;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private raven.tabbed.TabbedPaneCustom managecarlistingtable;
    private javax.swing.JTextField modelTF;
    private javax.swing.JButton refreshBTN;
    private javax.swing.JButton refreshbtn;
    private raven.tabbed.ShadowRenderer shadowRenderer1;
    private javax.swing.JTable tableViewbooking;
    private javax.swing.JTextArea txtAreaAnnouncements;

    private static javax.swing.JTextField txtFieldSearchManageCar;
    private static javax.swing.JTextField txtFieldSearchManageUser;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}